src/App.tsx
src/main.tsx
src/styles/GlobalStyles.ts

init: Global 스타일 적용, 폴더 구조 수정

---

.stylelintrc.json
package.json
src/components/common/Button/Button.style.ts
src/components/common/Button/index.tsx
src/styles/GlobalStyles.ts
yarn.lock

- close #8 
- 두 가지 버튼의 variant 명을 choose / complete로 구분 지어놨는데 더 나은 방법이 잇을가용?
-

[ Common ] Button 구현

---

package.json
src/libs/api.ts
yarn.lock

- close #56 
[.env 파일은 노션에 올려두겠습니당 ](https://www.notion.so/rileybyeon/env-cfcedc763d84478d84a8c46a7080e71b)

[ common ] axios 세팅

---

src/StickerPack/api/getStickerPack.ts
src/StickerPack/components/StickerList/StickerList.style.ts
src/StickerPack/components/StickerList/index.tsx
src/StickerPack/hooks/useGetStickerPack.ts
src/StickerPack/page/StickerPack/StickerPack.style.ts
src/StickerPack/page/StickerPack/index.tsx
src/StickerPack/type/stickerPackType.ts
src/libs/hooks/getStickerPack.ts

[ StickerPack ] 스티커팩 API 패칭 

---

src/StickerPack/components/StickerList/index.tsx
src/StickerPack/page/StickerPack/StickerPack.style.ts
src/StickerPack/page/StickerPack/index.tsx
src/StickerPack/type/stickerPackType.ts

Reverts Team-Lecue/Lecue-Client#70
ReVERT..?
이런..? 일이? ㅋㅋ
죄송합니다

Revert "[ StickerPack ] 선택된 스티커 데이터 라우트 이동"

---

src/StickerPack/components/StickerList/index.tsx
src/StickerPack/page/StickerPack/StickerPack.style.ts
src/StickerPack/page/StickerPack/index.tsx
src/StickerPack/type/stickerPackType.ts

[ Stickerpack ] develop 머지용 PR입니다!

---

src/LecueNote/components/CreateNote/CreateNote.style.ts
src/LecueNote/components/CreateNote/index.tsx
src/LecueNote/components/Footer/Footer.style.ts
src/LecueNote/components/Footer/index.tsx
src/LecueNote/components/SelectColor/SelectColor.style.ts
src/LecueNote/components/SelectColor/index.tsx
src/LecueNote/components/ShowColorChart/ShowColorChart.style.ts
src/LecueNote/components/ShowColorChart/index.tsx
src/LecueNote/components/WriteNote/WriteNote.style.ts
src/LecueNote/components/WriteNote/index.tsx
src/LecueNote/constants/colorChart.ts
src/LecueNote/page/LeceuNotePage/LecueNotePage.style.ts
src/LecueNote/page/LeceuNotePage/index.tsx
src/LecueNote/type/lecueNoteType.ts
src/Router.tsx
src/styles/GlobalStyles.ts

Merte Feature/create note into develop

---

src/Register/components/NicknameInput/NicknameInput.style.ts
src/Register/components/NicknameInput/index.tsx
src/Register/components/RegisterLogo/RegisterLogo.style.ts
src/Register/components/RegisterLogo/index.tsx
src/Register/components/SubmitButton/SubmitButton.style.ts
src/Register/components/SubmitButton/index.tsx
src/Register/page/Register.style.ts
src/Register/page/index.tsx
src/Router.tsx

- close #44 
https://github.com/Team-Lecue/Lecue-Client/assets/108219121/5176f8fb-3795-4122-a6ee-47c728cd4d75
없습니다!
이후에 API 붙일 때 서버로 값 보내기 전에 뒤에 공백 없애는 과정 추가 필요합니다!
타입 파일 따로 빼는지 궁금합니다..! 그리고 `NicknameInput` 컴포넌트 파일에 함수들도 같이 있는데 따로 파일을 빼는게 좋을지도 궁금합니다..

[ Register ] 닉네임 설정 뷰 퍼블리싱

---

src/LecueNote/components/CreateNote/index.tsx
src/LecueNote/components/SelectColor/index.tsx
src/LecueNote/components/ShowColorChart/ShowColorChart.style.ts
src/LecueNote/components/ShowColorChart/index.tsx
src/LecueNote/components/WriteNote/WriteNote.style.ts
src/LecueNote/components/WriteNote/index.tsx
src/LecueNote/page/LeceuNotePage/index.tsx
src/LecueNote/type/lecueNoteType.ts

- close #38 
https://github.com/Team-Lecue/Lecue-Client/assets/80264647/7758aa35-506b-48fd-9473-8e055f9f360b
- 없음니다~! 오랜만에 ㅋㅋ 신난당

[ CreateNote ] 이미지 업로드 기능 구현

---

src/Mypage/components/LecueList/LecueList.style.ts
src/Mypage/components/LecueList/index.tsx
src/Mypage/components/LecueNote/LecueNote.style.ts
src/Mypage/components/LecueNote/index.tsx
src/Mypage/constants/DATA.ts
src/Mypage/types/myPageType.ts

- close #84 
https://github.com/Team-Lecue/Lecue-Client/assets/108219121/a43f85b1-eb88-4dfd-a312-b4c258b5d046
X

[ Mypage ] 레큐노트 배경색상, 텍스트색상 적용

---

src/Mypage/components/LecueBook/index.tsx
src/Mypage/components/LecueList/index.tsx
src/Mypage/components/LecueNote/index.tsx
src/Mypage/types/myPageType.ts

- close #85 
https://github.com/Team-Lecue/Lecue-Client/assets/108219121/edba3cca-6710-41da-856b-90a145f0ee2b
- 이후에 모달창 뜨는거 구현하고 이벤트 함수에 붙일게용~

[ Mypage ] 레큐북, 레큐노트 클릭 이벤트

---

src/CreateBook/components/BookInfoTextarea/BookInfoTextarea.style.ts
src/CreateBook/components/BookInfoTextarea/index.tsx
src/CreateBook/components/BookInput/index.tsx
src/CreateBook/components/CompleteButton/CompleteButton.style.ts
src/CreateBook/components/CompleteButton/index.tsx
src/CreateBook/components/SelectColor/SelectColor.style.ts
src/CreateBook/components/SelectColor/index.tsx
src/CreateBook/components/ShowColorChart/index.tsx
src/CreateBook/constants/colorChart.ts
src/CreateBook/page/CreateBook.style.ts
src/CreateBook/page/index.tsx
src/CreateBook/utils/api.ts
src/SelectBook/page/SelectBookPage/SelectBookPage.style.ts
src/SelectBook/page/SelectBookPage/index.tsx

- close #109 
https://github.com/Team-Lecue/Lecue-Client/assets/60962533/53713fd5-5aeb-4f0f-945c-14cc50d7d514
localStorage에서 토큰 받아와서 사용하는 로직까지 구현되어 있습니다. localStorage key를 'token'으로 지정하고 구현했는데, 도리가 다르게 지정했다면 거기에 맞춰서 수정할 예정입니다~!!
p.s. 공통 모달 연결 및 PUT 로직 분리는 아직 미적용 상태입니다!

[ CreateBook ] 레큐북 생성 POST API 연동

---

src/Home/components/LecueBookList/index.tsx
src/Home/components/NavigateLecueBook/NavigateLecueBook.style.ts
src/Home/components/NavigateLecueBook/index.tsx
src/Home/page/Home.style.ts
src/Home/page/index.tsx
src/Router.tsx
src/Splash/component/Body/Body.style.ts
src/Splash/component/Bottom/Bottom.style.ts
src/Splash/component/Bottom/index.tsx
src/Splash/component/Header/Header.style.ts
src/Splash/page/SplashPage/SplashPage.style.ts
src/Splash/page/SplashPage/index.tsx

- close #117 
https://github.com/Team-Lecue/Lecue-Client/assets/80264647/b9685668-df4c-44fd-a409-60d1d94f988e
- 홈에서 버튼 클릭 시, 로그인 여부 판단 후 해당 페이지로 넘어가게 해뒀습니당
- 로그인 안되었다고 판단 -> 로그인 뷰로 이동
- 영상 찍을 때는 이 부분 잠시 주석처리하고 다른 페이지로 넘어가는지만 녹화했습니다.
- 머지 충돌나는데 왜인지 모르겠지만 해결하고 오겠습니당~!
- 해결 완 ~

[ Home ] 라우팅

---

src/LecueNote/components/CreateNote/index.tsx
src/LecueNote/components/Footer/index.tsx
src/LecueNote/components/SelectColor/index.tsx
src/LecueNote/components/ShowColorChart/index.tsx
src/LecueNote/page/LeceuNotePage/index.tsx
src/LecueNote/type/lecueNoteType.ts

- close #127 
- 보여지는 기능 자체는 이전과 동일해요
- props가 너무 많아져서 .. . . 흠 어찌해야 할지 모르겠네요 일단 곧 정리해볼 예정입니다.

[ CreateNote ] presigned url put 통신위치 변경

---

src/StickerPack/api/getStickerPack.ts
src/StickerPack/page/StickerPack/index.tsx

- close #52
https://github.com/Team-Lecue/Lecue-Client/assets/65286685/bd908481-1f60-4813-96e6-a868b1c0ae69

[ StickerPack ] 로그인 분기 처리

---

src/Detail/components/LecueNoteListContainer/index.tsx
src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts
src/Detail/components/ZigZagView/index.tsx
src/StickerPack/components/StickerList/index.tsx

- close #137
https://github.com/Team-Lecue/Lecue-Client/assets/65286685/766909d2-10b7-43a3-bd7b-6099f6c64a3e

[ StickerAttach ] 스티커 위치 바닥으로부터 잡기

---

src/Mypage/api/getMyBookList.ts
src/Mypage/api/getMyNickName.ts
src/Mypage/api/getMyNoteList.ts
src/Mypage/components/LecueBook/index.tsx
src/Mypage/components/LecueList/index.tsx
src/Mypage/components/LecueNote/index.tsx
src/Mypage/components/Nickname/index.tsx
src/Mypage/components/NoteModal/NoteModal.style.ts
src/Mypage/components/NoteModal/index.tsx
src/Mypage/hooks/useGetMyBookList.ts
src/Mypage/hooks/useGetMyNickname.ts
src/Mypage/hooks/useGetMyNoteList.ts
src/Mypage/types/myPageType.ts

- close #48
https://github.com/Team-Lecue/Lecue-Client/assets/65286685/3f2fd6de-141d-4812-824b-a76a0fd61c94

[ myPage ] API 패칭

---

src/Mypage/api/deleteMyBook.ts
src/Mypage/components/LecueBook/index.tsx
src/Mypage/components/NoteModal/index.tsx
src/Mypage/hooks/useDeleteMyBook.ts

- close #50
- 현재 모달에 실행함수가 안붙어 삭제 로직은 주석처리 후 모달만 달아두었습니다!

[ Mypage ] 레큐북 삭제 구현

---

src/Target/components/FavoriteImageInput/index.tsx
src/Target/hooks/useGetPresignedUrl.ts
src/Target/hooks/usePutPresignedUrl.ts
src/Target/page/TargetPage/index.tsx
src/Target/util/api.ts

- close #152 
Command + Tab을 누르거나 화면 밖으로 포커스를 옮기면 GET 요청이 계속 다시 날아갑니다... 뭐지....? 원래 React-Query의 기능 중 하나인가요....?
p.s.커밋 잘못 날려서 revert 하려다가 잘못돼서 revert라는 커밋 메시지로 새로운 커밋이 또 생긴 썰 풉니다.....😅

[ TargetPage ] React-Query 연결

---

src/Detail/api/getBookDetail.ts
src/Detail/components/LecueNoteListContainer/AlretBanner/AlertBanner.style.ts
src/Detail/components/LecueNoteListContainer/AlretBanner/index.tsx
src/Detail/components/LecueNoteListContainer/LecueNoteListContainer.style.ts
src/Detail/components/LecueNoteListContainer/index.tsx
src/Detail/components/ZigZagView/ZigZagView.style.ts
src/Detail/components/ZigZagView/index.tsx
src/Detail/hooks/useGetBookDetail.ts
src/Detail/page/DetailPage/index.tsx
src/Router.tsx
src/StickerAttach/api/postStickerState.ts
src/StickerAttach/hooks/usePostStickerState.ts
src/StickerPack/api/getBookUuid.ts
src/StickerPack/api/getStickerPack.ts
src/StickerPack/hooks/useGetBookUuid.ts
src/StickerPack/page/StickerPack/index.tsx

[ StickerAttach ] 다이나믹 라우팅 연결

---

src/Splash/api/getNoteNum.ts
src/Splash/component/Body/index.tsx
src/Splash/hook/useGetNoteNum.ts
src/Splash/page/SplashPage/index.tsx

Merge Feature/splash into develop

---

src/Home/components/LecueBookList/LecueBookList.style.ts
src/Home/components/NavigateLecueBook/NavigateLecueBook.style.ts

[ Home ] UI 디자인 수정

---

src/Detail/components/LecueNoteListContainer/LecueNoteListContainer.style.ts

[ DetailPage ] DetailView height bugfix

---

src/LecueNote/components/WriteNote/WriteNote.style.ts
src/LecueNote/components/WriteNote/index.tsx

Merge CreateNote into dev

---

src/App.tsx
src/Detail/components/LecueNoteLIstHeader/LecueNoteListHeader.style.ts
src/LecueNote/components/WriteNote/WriteNote.style.ts
src/LecueNote/constants/colorChart.ts

Merge Hotfix rooming into dev

---

src/CreateBook/hooks/usePostBook.ts
src/CreateBook/page/index.tsx

[ CreateBook ] React-Query 연결 

---

src/Detail/hooks/useGetBookDetail.ts
src/Home/hooks/useGetLecueBook.ts
src/LecueNote/hooks/useGetPresignedUrl.ts
src/Mypage/hooks/useGetMyBookList.ts
src/Mypage/hooks/useGetMyNickname.ts
src/Mypage/hooks/useGetMyNoteList.ts
src/Splash/hook/useGetNoteNum.ts
src/StickerPack/hooks/useGetBookUuid.ts
src/StickerPack/hooks/useGetStickerPack.ts
src/Target/hooks/useGetPresignedUrl.ts
src/Target/util/api.ts

- close #189 
https://github.com/Team-Lecue/Lecue-Client/assets/60962533/d0e919e5-4183-43ca-be39-84cd1f1b324b

[Hotfix] refetchOnWindowFocus Error Fix

---

src/Detail/components/ZigZagView/ZigZagView.style.ts
src/Detail/hooks/useGetBookDetail.ts
src/LecueNote/page/LeceuNotePage/index.tsx
src/Router.tsx
src/components/common/ErrorPage/index.tsx

[ HotFix ] Develop으로 가라!

---

src/CreateBook/hooks/usePostBook.ts
src/CreateBook/page/index.tsx

[Hotfix] usePostBook Error Fix

---

src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts
src/Mypage/components/LecueBook/LecueBook.style.ts
src/Mypage/components/LecueBook/index.tsx
src/Mypage/components/LecueNote/LecueNote.style.ts
src/Mypage/components/NoteModal/NoteModal.style.ts
src/Mypage/hooks/useDeleteMyBook.ts

[ Hotfix ] Dev 머지머지

---

src/Home/components/NavigateLecueBook/NavigateLecueBook.style.ts
src/Register/components/NicknameInput/index.tsx
src/Register/hooks/usePatchNickname.ts
src/Register/page/index.tsx

[ Register ] 에러 핸들링 추가

---

src/Detail/components/BigLecueNote/BigLecueNote.style.ts
src/Detail/components/BigLecueNote/index.tsx
src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts
src/Detail/components/LecueNoteModal/index.tsx
src/Detail/components/SmallLecueNote/SmallLecueNote.style.ts
src/Detail/components/SmallLecueNote/index.tsx
src/Detail/type/lecueBookType.ts

[ Hotfix ] Dev 머지

---

src/Router.tsx
src/components/common/BoundaryErrorPage/BoundaryErrorPage.style.ts
src/components/common/BoundaryErrorPage/index.tsx

feat: 에러바운더리 컴포넌트 갈아끼우기

---

index.html
src/LecueNote/components/ShowColorChart/index.tsx
src/LecueNote/hooks/useGetPresignedUrl.ts

Merge Hotfix rooming into develop

---

deploy/Dockerfile
package.json
vite.config.ts

- close #226 
- 사실 develop 넘겨봐야지 확실히 동작 되는지 확인할 수 있을 것 같아서 merge 시켜주십시와용 (로컬에선 문제 없이 build 되긴했습니당 ㅜ.ㅜ
- 어쩐지 배포된게 느리더라니...

[ Common ] 프로덕션 환경으로 배포

---

index.html
public/robots.txt

- close #224 
- 검색이 전혀 되지 않고 있어 임시로 메타 태그 몇가지 추가하고, robots 추가했습니다.
- 우선은 최대한 방어적으로 수정해두었습니다. 레큐북 단위의 메타 데이터 추가는 킥오프 이후 추후 스프린트 회의에서 논의 후 반영하겠습니다.

[ Common ] meta태그 추가. robots.txt 추가

---

package.json
src/LecueNote/components/SelectColor/index.tsx
src/LecueNote/components/ShowColorChart/index.tsx
src/LecueNote/components/WriteNote/NoteLoading/NoteLoading.style.ts
src/LecueNote/components/WriteNote/NoteLoading/index.tsx
src/LecueNote/components/WriteNote/WriteNote.style.ts
src/LecueNote/components/WriteNote/index.tsx
src/LecueNote/page/LeceuNotePage/index.tsx
src/LecueNote/reducer/lecueNoteReducer.ts
src/LecueNote/type/lecueNoteType.ts
src/LecueNote/type/reducerType.ts
src/LecueNote/util/handleClickFiletoBinary.ts
src/LecueNote/util/handleClickFiletoString.ts
src/LecueNote/util/handleClickHeicToJpg.ts
yarn.lock

dev로 들어가걸아ㅏ ~~!!!!!!!!

---

src/Mypage/api/getMyNickName.ts

- close #276 
이전에는 노트 GET api였다면, 이제는 다른 api로 분리되어 url만 변경해주었습니다!

[ Mypage ] 마이페이지 조회 (닉네임 GET API) 수정사항 반영

---

README.md
index.html
src/Detail/components/EmptyView/index.tsx
src/LecueNote/page/LeceuNotePage/index.tsx
src/Mypage/components/EmptyView/index.tsx
src/Mypage/components/LecueList/index.tsx
src/SelectBook/page/SelectBookPage/index.tsx
src/Splash/component/Body/index.tsx
src/components/common/Modal/constants/ModalContents.tsx

[ Common ] 레큐 노트를 레터로 명칭 변경

---

src/Enter/page/index.tsx

- close #288 
https://github.com/Team-Lecue/Lecue-Client/assets/108219121/f9fe2e29-21f6-4ba0-83f1-1c287f6017e2
로그아웃 버튼 클릭하면  로컬스토리지 비우고, 이후에 `Home`으로 가도록 해두었습니다 (예솔이와 상의 완료). 모달창 대신에 confirm으로 확인을 누르면 로그아웃, 취소를 누르면 아무런 이벤트가 없도록 구현해보았습니다.
X

[ Mypage ] 로그아웃 구현

---

src/Enter/page/index.tsx

- close #290 
https://github.com/Team-Lecue/Lecue-Client/assets/108219121/123048f4-d6c0-4fee-bb44-e8a35167a7a5
외교부 사람들과 상의한 뒤 각각 어떤 링크를 연결할지 정해보았습니다. (팀 소개 - 인스타 / 공지사항 - 노션 / 문의하기 - 구글폼) 그리고 우선 전부 다 새 창으로 열리도록 `target="_blank"` 를 추가해두었습니다..! 
X

[ Mypage ] 외부 링크 연결

---

src/History/components/MyLecueBook/index.tsx

fix: build error 해결

---

src/Home/components/NoBookmarkList/index.tsx

hot-fix: 라우팅 수정

---

src/Target/components/NameInput/index.tsx
src/Target/page/TargetPage/index.tsx

[ TargetPage ] 레큐북 제작 뷰 최애 워딩 수정

---

src/History/components/MyLetter/MyLetter.style.ts
src/History/components/MyLetter/index.tsx
src/History/types/historyType.ts

[ Mypage ] 내기록보기 - 사용자가 지정한 배경 / 텍스트 색 반영

---

src/Detail/hooks/useGetBookDetailLogin.ts
src/History/components/MyLecueBook/index.tsx
src/History/hooks/useDeleteMyBook.ts
src/History/hooks/useGetMyBookList.ts
src/History/hooks/useGetMyFavorite.ts
src/constants/queryKeys.ts
src/libs/hooks/useDeleteFavorite.ts
src/libs/hooks/useGetFavorite.ts
src/libs/hooks/usePostFavorite.ts

[ Hotfix ] 쿼리 키 싱크 맞추기
