src/StickerPack/components/StickerList/index.tsx, src/StickerPack/page/StickerPack/StickerPack.style.ts, src/StickerPack/page/StickerPack/index.tsx, src/StickerPack/type/stickerPackType.ts
=> [ StickerPack ] 선택된 스티커 데이터 라우트 이동

src/LecueNote/components/CreateNote/CreateNote.style.ts, src/LecueNote/components/CreateNote/index.tsx, src/LecueNote/components/Footer/index.tsx, src/LecueNote/components/SelectColor/SelectColor.style.ts, src/LecueNote/components/SelectColor/index.tsx, src/LecueNote/components/ShowColorChart/ShowColorChart.style.ts, src/LecueNote/components/ShowColorChart/index.tsx, src/LecueNote/components/WriteNote/WriteNote.style.ts, src/LecueNote/components/WriteNote/index.tsx, src/LecueNote/page/LeceuNotePage/LecueNotePage.style.ts, src/LecueNote/page/LeceuNotePage/index.tsx, src/LecueNote/type/lecueNoteType.ts, src/assets/icon/ic_camera_small.svg, src/assets/index.ts
- close #35 
https://github.com/Team-Lecue/Lecue-Client/assets/80264647/aea0b54a-4386-49c6-a864-e8f50b55dd3d
https://github.com/Team-Lecue/Lecue-Client/assets/80264647/38e25bb8-435c-43d5-948f-f0fc65d6a0ef
- 막상 구현해보니 생성일자가 눈에 너무 안띄어서 이 부분 말씀드려볼 예정입니다.
- 글자 수가 1000자 이상일 경우, 지금은 별다른 경고창 없이 1000자만큼 글자가 잘립니다!
- 개인적으로는 이 부분 UX가 좋지 않은 것 같아서, 이 부분 역시 말씀드려보고 가능하다면 alert나 모달 등을 추가할 예정입니다.
=> [ CreateNote] 레큐 노트 내부 기능 구현

src/Detail/components/LecueNoteListContainer/index.tsx, src/Detail/components/ZigZagView/ZigZagView.style.ts, src/Detail/components/ZigZagView/index.tsx, src/Detail/page/DetailPage/index.tsx, src/StickerAttach/hooks/usePostStickerState.ts
=> [ StickerAttach ] 스크롤 위치 복원 + 버그 픽스

src/Detail/components/LecueNoteModal/index.tsx, src/Detail/components/SmallLecueNote/index.tsx, vite.config.ts
- close #135 
https://github.com/Team-Lecue/Lecue-Client/assets/60962533/1f7df349-894b-474f-9a87-a9c040c91209
모달이 열리고 X버튼을 눌러도 modalShow가 true로 유지되면서 모달이 닫히지 않는 문제가 있었습니다.
문제를 해결하기 위해 호출 순서를 추적했는데, X 버튼을 눌렀을 때 자식 컴포넌트인 LecueNoteModal의 클릭 이벤트 핸들러가 먼저 동작한 직후 부모 컴포넌트인 SmallLecueNote의 클릭 이벤트 핸들러도 같이 동작하여  modalShow가 false -> true로 바뀌며 결국 true로 유지되는 문제였습니다.
=> 결국 하위 컴포넌트의 클릭 이벤트가 상위 컴포넌트로 전파되는 상황이기에 이벤트 버블링 문제라고 생각했고, X 버튼 클릭 이벤트 핸들러에  event.stopPropagation();을 추가해주어 이벤트 버블링을 차단시켰습니다. 그 결과 정상적으로 X 버튼을 누를 때만 모달이 닫히게 되었습니다 🙂
=> [ DetailPage ] Modal X 버튼 클릭 시 삭제 Event 바인딩 오류 FIX

src/Detail/components/LecueNoteModal/index.tsx, src/Detail/components/SmallLecueNote/index.tsx
- close #232 
- 기존에 SmallLecueNote 컴포넌트 최상단 태그에 onClick 이벤트 핸들러가 바인딩되어 있었고,  그 자식 컴포넌트로 onClick 이벤트 핸들러가 바인딩되어있는 LecueNoteModal 컴포넌트가 위치하여 이벤트 버블링이 발생하였습니다. LecueNoteModal은 전체 뷰포트 기준 중앙에 오버레이되기 때문에 굳이 SmallLecueNote 컴포넌트 하위에 위치할 필요가 없다고 판단하였습니다. 그래서 LecueNoteModal 컴포넌트를 기존 SmallLecueNote 컴포넌트 최상단 태그와 같은 레벨에 위치시키고, `<React.Fragment>`로 이 둘을 감싸주었습니다.
=> [ Detail ] Event Bubbling 방지를 위한 코드 구조 수정

src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts
- close #230 
- background-size 속성을 cover에서 컴포넌트 width, height 사이즈로 맞춰주었습니다.
=> [ Detail ] 사진을 배경으로 하는 레큐 노트 클릭 시, 모달에서 사진 줌되는 이슈

src/Mypage/components/EmptyView/index.tsx, src/Mypage/components/LecueBook/index.tsx, src/Mypage/components/LecueList/LecueList.style.ts, src/Mypage/components/LecueList/index.tsx, src/Mypage/components/LecueNote/index.tsx, src/Mypage/components/NoteModal/index.tsx, src/Mypage/types/myPageType.ts
- close #222 
1. 레큐북 / 레큐노트 선택함에 따라 해당 컴포넌트의 스크롤이 최상단으로 되도록 구현해두었는데 컴포넌트 구조를 바꾸면서 구현했던 것이 제대로 작동 안하는걸 이제야 깨달아서 수정해두었습니다..!
2. state를 변경하는 함수를 직접 내려주지 않고 핸들러 함수로 감싸준 뒤 props로 전달하도록 수정했습니당
=> [ Mypage ] 코드 리팩토링

src/Register/components/NicknameInput/index.tsx, src/Register/components/SubmitButton/index.tsx, src/Register/hooks/useCheckNickname.ts, src/Register/hooks/usePatchNickname.ts, src/Register/page/index.tsx, src/Register/types/registerTypes.ts, src/Register/utils/checkInputRange.ts, src/Register/utils/handleCheckInput.ts
- close #223 
닉네임 유효성 검사하는 함수들을 별도의 hook으로 분리해보았습니다..! 이게 맞는지 확신은 서지 않지만 닉네임을 입력받는 input 컴포넌트 파일에 있는 유효성 검사 함수들을 따로 분리하고, 해당 컴포넌트는 닉네임을 입력 받는 단일 역할을 주는게 좀 더 맞다고 생각했기 때문이죠 ..
=> [ Register ] 타입 / 닉네임 유효성 검사 로직 분리

src/Login/components/LoginCallback/LoginCallback.tsx
- close #231 
로딩뷰와 어떻게 연결할까 고민하다가 `LoginCallback.tsx` 컴포넌트에 `LoadingPage` 컴포넌트 import해서 리턴시키는 방법을 사용했습니다. redirect url이 다르고, 해당 페이지가 마운트 되었을 때 실행되어야하는 동작들이 있기 떄문에 로딩페이지 컴포넌트를 그대로 사용하는 대신 컴포넌트를 로그인콜백이라는 새로운 컴포넌트를 만들어서 사용해야겠다는 생각이 들었습니다... 혹시 다른 방법이 더 있을까 궁금하긴 하네용..
+해당 PR을 `Login/#229-query-attach`로 머지한 뒤에, `Login/#229-query-attach`에서 한번에 `refactor/Login`으로 머지 할게요!
=> [ Login ] LoginCallback 페이지 수정

src/Login/api/getLoginToken.ts, src/Login/api/postLoginToken.ts, src/Login/components/LoginCallback/LoginCallback.tsx, src/Login/hooks/useGetLoginToken.ts, src/Login/hooks/usePostLoginToken.ts, src/Register/hooks/usePatchNickname.ts
- close #229 
컴포넌트에서 쿼리 적용한 useGetLoginToken을 아무리 호출해도 리턴값이 넘어오지 않더라구요 ..? (useGetLoginToken이 onSuccess일 때, 카카오 서버에서 받아온 response 안에 있는 access_toekn을 리턴해주려 했습니다!) 그래서 좀 더 공부를 해오니 리턴값을 넘겨줄 수 없다 ..! 라는 것을 새롭게 알게 되어서 `loginToken` 이라는 state를 새롭게 만들게 되었습니다..! 이 방법이 최선일까요? 🥺
=> [ Login ] React-Query 적용

src/Detail/components/ZigZagView/ZigZagView.style.ts
- close #219 #221
-
- 가장 좋은 방법은 배열에서 삭제시키는 것일 것 같은데 현재 각 스티커 하나씩을 post하고, 서버측에서 배열에 담아주고 있어서 서버랑 논의 해보아야할 것 같습니다. 
- 처음부터 height값을 제대로 못 읽어오는 문제는 충돌 문제가 있을 것 같아 https://github.com/Team-Lecue/Lecue-Client/pull/225 해당 PR에서 진행했습니다!
=> [ StickerAttach ] 스티커 overflow 수정

src/Detail/components/LecueNoteListContainer/index.tsx
=> [ HOTFIX ] 스티커 post 불가 버그

package.json, src/LecueNote/components/SelectColor/index.tsx, src/LecueNote/components/ShowColorChart/index.tsx, src/LecueNote/components/WriteNote/NoteLoading/NoteLoading.style.ts, src/LecueNote/components/WriteNote/NoteLoading/index.tsx, src/LecueNote/components/WriteNote/WriteNote.style.ts, src/LecueNote/components/WriteNote/index.tsx, src/LecueNote/page/LeceuNotePage/index.tsx, src/LecueNote/reducer/lecueNoteReducer.ts, src/LecueNote/type/lecueNoteType.ts, src/LecueNote/type/reducerType.ts, src/LecueNote/util/handleClickFiletoBinary.ts, src/LecueNote/util/handleClickFiletoString.ts, src/LecueNote/util/handleClickHeicToJpg.ts, yarn.lock
- close #220 
- `heic2any` 라이브러리를 활용하여 heic/ HEIC -> jpeg 파일로 변환해주었습니다.
- `isLoading` state를 만들어서 로딩 처리를 해주었습니다.
- `localStorage`를 활용하여 heic 파일을 업로드 하더라도 화면 상의 이전 내용이 유지되도록 구현했습니다.
- 형변환 과정에서도 이미 시간이 좀 걸리고 localStorage에 저장된 노트 내용을 불러오는 과정에서도 시간이 걸려서 로딩 과정이 꽤 긴 편인데요, 이걸 어떻게 하면 해결할 수 있을까요?
- 테스트 해보니 heic 파일이 아이폰으로 넘어오면 heif로 바껴서 딱히 형변환 없이도 잘 올라가긴 합니다만,, 위의 문제를 해결할 법한 뾰족한 수가 떠오르지 않네용 흑흑
- 아이폰의 heif 파일 -> 데탑으로 넘어오면 heic로 바뀜.
=> [ CreateNote ] 이미지 확장자(heic)에 따라 업로드 안되는 이슈 해결

src/Home/page/index.tsx
- close #256 
https://github.com/Team-Lecue/Lecue-Client/assets/80264647/ff9b90e0-cff4-4cc2-aea3-93d678aebc59
- 로컬스토리지에 엑세스토큰이 저장되어 있는지 여부에 따라 보여지는 컴포넌트가 다르게 구현했습니다.
- 로컬스토리지에 저장된 엑세스토큰이 있는 경우에만, 즐겨찾기 컴포넌트를 띄워줍니다.
=> [ Home ] 로그인 여부에 따른 분기처리

src/Home/components/LecueBookList/LecueBookList.style.ts, src/Home/components/LecueBookList/index.tsx
- close #255 
https://github.com/Team-Lecue/Lecue-Client/assets/80264647/19cc7ba7-e9eb-480f-a5a5-c696563b7b3a
- 아직 즐겨찾기 리스트를 불러오는 api가 나오지 않아서, 임시로 인기 레큐북 데이터를 즐겨찾기 컴포넌트의 데이터로 넣어서 작업했습니다.
- 즐겨찾기 아이콘 클릭 시, delete 메소드를 통해 기존 즐겨찾기 리스트에 있는 데이터를 지울 것 같습니다.
- 아직 즐겨찾기 삭제 관련 api도 나오지 않은 상태라, 즐겨찾기 아이콘 클릭 시 해당 레큐북의 `display: none` 처리 해두었습니다.
- 이 과정에서 IconWrapper의 액션 핸들러보다 LecueBook의 액션핸들러가 먼저 동작하는 이슈가 있어서 `e.stopPropagation()` 한 줄 추가해줬습니다.
- 앞서 구현한 IconWrapper의 액션 핸들러 관련 코드는 api가 나오면 모두 서버통신 코드로 바꿔줄 예정입니다 !!
=> [ Home ] 즐겨찾기 아이콘 클릭 시 즐겨찾기에서 삭제

src/Mypage/page/Mypage.style.ts, src/Mypage/page/index.tsx
- close #263 
MypageBodyWrapper 안에 갈아낄 컴포넌트들 렌더시키면 될 것 같습니다아!!
기존 컴포넌트들 재사용 가능성이 있어 일단은 삭제 안 하고 남겨뒀습니다~!
=> [ Mypage ] Header를 포함한 Mypage 기본 프레임 구현

src/Mypage/components/HistoryEnterView/HistoryEnterView.style.ts, src/Mypage/components/HistoryEnterView/index.tsx
- close #262 
추후에 일러스트가 들어간다고 합니다.. 일러스트가 들어가면 뷰에 또 변화가 있다고 하니 일단은 피그마에 있는대로 만들어둘게용..! 각 요소를 눌렀을 때의 컴포넌트 교체는 정우가 할 겁니다..! 페이지 라우팅은 이전PR(#266) 머지하고 적용해둘게요!
XXXX
=> [ Mypage ] 내 기록보기 진입 페이지 뷰 구현

src/Detail/components/BigLecueNote/BigLecueNote.style.ts, src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts, src/LecueNote/components/ShowColorChart/ShowColorChart.style.ts
- close #314 
- 노트 내용 부분이 `overflow: scroll`로 설정되어 있어서 내용이 넘치지 않아도 무조건 스크롤이 생기는 이슈였습니다!
- 처음엔 `overflow: auto`를 줘서 한 번에 스크롤을 다루려고 했는데요, 요렇게 했더니 내용이 길어지면 y축 뿐만 아니라 x축까지 스크롤이
생겨버리더라구요!
- 저희는 가로 스크롤은 필요가 없기 때문에, `overflow: hidden auto`로 수정하여 x축 스크롤은 무조건 막고 
내용물의 길이가 노트 높이보다 길어질 경우 y축에만 스크롤이 생기도록 했습니다 !!~
=> [ LecueNote ] 윈도우 상에서 노트 위에 스크롤 생기는 이슈 해결

src/History/components/MyLecueBook/index.tsx, src/History/hooks/useDeleteMyBook.ts, src/History/hooks/useGetMyBookList.ts, src/components/common/LecueBook/index.tsx, src/libs/hooks/useDeleteFavorite.ts, src/libs/hooks/usePostFavorite.ts
- close #315 
https://github.com/Team-Lecue/Lecue-Client/assets/108219121/a0c7d243-c071-4526-8bad-7e2402b65a9f
즐겨찾기를 추가했을 때 -> 우선 즐겨찾기를 추가하는 경우는 (1) 마이페이지 - 내가 만든 레큐북에서 추가하는 경우 밖에 없어서 즐겨찾기 post hook에서 성공했을 때, getMtLecueBook api를 refetch하도록 변경해두었습니다! 나중에 레큐북 상세보기에서 즐겨찾기를 추가할 수 있게 된다면 요것도 case를 나눠주어야 할 듯 싶습니다..!
즐겨찾기를 해제했을 때 -> (1)홈에서 즐겨찾기를 해제한 경우 / (2)마이페이지 - 즐겨찾기한 레큐북에서 즐겨찾기를 해제한 경우 / (3) 마이페이지 - 내가 만든 레큐북에서 즐겨찾기를 해제한 경우, 요렇게 즐겨찾기를 해제하는 경우가 총 세가지가 있는데, 세 경우에 다시 호출해야하는 api가 달라서 switch - case 문으로 각각 필요한 api를 호출해주는 방식으로 변경했습니다!
```
onSuccess: () => {
switch (state) {
case 'home':
queryClient.refetchQueries(['get-favorite'], {
exact: true,
});
break;
case 'favoriteBook':
queryClient.refetchQueries(['get-mypage-favorite'], {
exact: true,
});
break;
case 'myLecueBook': …
```
=> [ Mypage ] 내가 만든 레큐북, 즐겨찾기한 레큐북 싱크 안 맞음

src/App.tsx, src/History/components/MyLecueBook/index.tsx, src/History/hooks/useDeleteMyBook.ts, src/History/hooks/useGetMyBookList.ts, src/History/hooks/useGetMyFavorite.ts, src/Home/constants/homeQueryKey.ts, src/Home/hooks/useGetLecueBook.ts, src/LecueNote/hooks/usePostLecueNote.ts, src/LecueNote/hooks/usePutPresignedUrl.ts, src/LecueNote/page/LeceuNotePage/index.tsx, src/components/common/LecueBook/index.tsx, src/constants/queryKeys.ts, src/libs/hooks/useDeleteFavorite.ts, src/libs/hooks/useGetFavorite.ts, src/libs/hooks/useGetMyNickname.ts, src/libs/hooks/usePostFavorite.ts
- close #322 
<br />
아무런 장치없이 컴포넌트 밖에 선언해줌 → 렌더링마다 새로운 리소스 생성
즉, 계속해서 리렌더링이 발생할 경우, QueryClient를 계속 다시 생성하는 것!
```jsx
const queryClient = new QueryClient({
defaultOptions: {
queries: {
suspense: true,
useErrorBoundary: true,
retry: 0,
},
},
});
```
<br />
state는 setter를 호출할 경우에만 업데이트 → setter를 선언하지 않음으로써 setter를 호출하지 않음
즉, `참조 동일성`을 유지할 수 있음 !
컴포넌트 라이프사이클 당 한 번만 리소스를 생성함
코드는 문제없이 실행되지만, 해당 값이 사용되지 않거나 필요하지 않더라도 렌더링할 때마다 해당 코드를 실행하게 된다고 함 !
```jsx
const [queryClient] = useState(
new QueryClient({
defaultOptions: {
queries: {
suspense: true,
useErrorBoundary: true,
retry: 0,
},
},
}),
);
```
**useState에 함수를 전달**하면 React는 초기 값이 필요할 때(컴포넌트가 처음 렌더링될 때)만 함수 호출
즉, initalState에 함수를 전달하면 **queryClient는 초기 한번만 생성되고, 이후에는 참조 동일성을 유지**하게 됨 !!
```tsx
const [queryClient] = useState(
() =>
new …
```
=> [ Common ] 코드 리팩토링

src/libs/api.ts
- close #339 
개선 이전 (콘솔창 봐보면 인스턴스가 반복해서 생성되고 있음!)
https://github.com/Team-Lecue/Lecue-Client/assets/108219121/d6a62d06-12d1-42d7-b34c-fed7d1a0901d
개선 이후(처음 인스턴스 생성 이후에 다시 생성되지 않음!)
https://github.com/Team-Lecue/Lecue-Client/assets/108219121/245cae91-4c2a-421f-b595-9b0148c13fd3
이전 코드
```
import axios from 'axios';
export const api = () => {
const api = axios.create({
baseURL: import.meta.env.VITE_APP_BASE_URL,
});
const token = sessionStorage.getItem('token');
api.defaults.headers.common['Authorization'] = `Bearer ${token}`;
return api;
};
```
개선된 코드
```
import axios, { AxiosInstance } from 'axios';
let apiInstance: AxiosInstance | null;
export const api = () => {
if (!apiInstance) {
apiInstance = axios.create({
baseURL: import.meta.env.VITE_APP_BASE_URL,
});
}
const token = …
```
=> [ Common ] Axios Instance 반복 생성 개선

src/Login/hooks/usePostLoginToken.ts, src/Login/page/index.tsx, src/Register/api/patchNickname.ts, src/Register/hooks/usePatchNickname.ts
- close #348 
회원가입 후 닉네임 설정 시 발생하는 401 에러를 해결했어요.
`api.ts` 모듈 구현을 살펴보면 이유를 알 수 있는데, 
```ts
const token = sessionStorage.getItem('token');
if (token) {
const headerToken = apiInstance.defaults.headers.common.Authorization;
if (!headerToken || token !== headerToken.toString().split(' ')[1]) {
apiInstance.defaults.headers.common['Authorization'] = `Bearer ${token}`;
}
}
```
sessionStorage 토큰이 존재할때만 토큰을 헤더에 심은 인스턴스를 반환하도록 설계되어있었어요.
저희 회원가입 플로우 상 카카오 인증을 완료한 후 닉네임을 입력하지 않으면 회원가입이 처리되지 않는 플로우로 구현되어 있었고, 회원가입이 완료되어야만 sessionStorage에 토큰을 저장하였어요.
하지만 닉네임 페이지에서는 회원가입이 아직 완료되지 않은 상태이기 때문에 sessionStorage에 토큰이 존재하지 않았고, 반환받은 api 모듈이 토큰을 header에 탑재하지 않은 상태였기 때문에 401 에러가 발생한 것이었어요.
그래서 저 경우에만 반환받은 api 인스턴스 header에 토큰을 직접 심어 Request하도록 수정했습니다.
```ts
export const patchNickname = async (nickname: string, …
```
=> [ BugFix ] 닉네임 설정 401 Error을 해결합니다.

src/Target/page/TargetPage/index.tsx
- close #350 
레큐 북을 제작할 때 400에러가 발생하는 이슈가 있었고, 에러 메시지를 확인해보니 아래와 같이 최애 이름은 1자 이상 15자 이하로 지정하라는 내용이 있었어요. 또한, response를 자세히 보니 최애 이름과 레큐 북 사진 부분에 아무런 데이터도 들어가지 않는 모습을 확인할 수 있었어요.
최애 이름과 레큐북 사진을 입력하는 페이지에서 콘솔로 해당 내용을 확인해보니, 최애 이름과 레큐북 사진 데이터가 잘 들어오고 있었어요.
그런데 완료 버튼을 눌렀을 때 실행되는 함수 내부에서는 콘솔에 아무런 내용도 찍히지 않더라구요.
해당 함수를 다시 살펴보니 useCallback으로 정의되어 있었는데 의존성이 빈 배열로 되어있어서, 최애 이름과 레큐북 사진 데이터가 들어오더라도 함수 내부에서는 변경된 내용이 입력되지 않고 있었어요.
의존성에 `name, fileData, presignedFileName`을 추가해주어 문제를 해결했어요.
=> [ Hotfix ] 레큐 북 제작 시 발생하는 400 에러 해결

src/Detail/components/LecueNoteListContainer/index.tsx, src/Detail/page/DetailPage/index.tsx
- close #352 
레큐북 뷰 초기 진입 시 붉은 박스가 나타났다 사라지는 이슈를 해결했어요.
원인은 `isEditable` 상태관리 때문이었어요.
기존에는 컴포넌트가 mount되면서 `isEditable`의 초기 상태가 `true`로 설정되고,
```tsx
const [isEditable, setIsEditable] = useState(true);
```
useEffect문 안에 들어가서 스티커 부착 모드가 아니면 `setEditableStateFalse()`으로 isEditable state를 false로 set하고 있었어요.
```tsx
useEffect(() => {
if (location.state) {
const { stickerId, stickerImage } = location.state.sticker;
window.scrollTo(0, savedScrollPosition);
setStickerState((prev) => ({
...prev,
postedStickerId: stickerId,
stickerImage: stickerImage,
}));
} else {
setEditableStateFalse();
}
}, [location.state, isEditable]);
```
또 붉은 테두리는 스티커 컴포넌트의 영역을 표시하는 border인데, isEditable이 true면 영역을 표시하도록 로직이 짜여 있었어요.
useEffect는 초기 Mount 이후에 로직을 실행하므로, useEffect 로직이 돌아 isEditable이 false로 세팅되기 전 찰나에 border가 …
=> feat: 레큐북 뷰 초기 진입 시 붉은 박스가 나타났다 사라지는 이슈를 해결합니다.

src/Detail/page/DetailPage/index.tsx
- close #355
레큐북 뷰 초기 진입 시 스티커 부착 뷰가 렌더링되는 이슈를 수정했어요.
#353 에서 state의 초기값을 false로 세팅했다고 했는데, 변경사항이 적용이 안 되었는지 true인 상태로 머지가 되어버렸더라구요.....
빠르게 수정했습니다!!!!!
@doyn511 QA 고마워요 🚀🚀
=> [ Hotfix ] 레큐북 뷰 초기 진입 시 스티커 부착 뷰가 렌더링되는 이슈를 수정합니다.

src/Detail/components/BookInfoBox/index.tsx, src/libs/hooks/useDeleteFavorite.ts, src/libs/hooks/usePostFavorite.ts
- close #358 
https://github.com/user-attachments/assets/21c282a8-831d-4ded-9d2b-29a321ac792d
레큐 북의 상세 페이지에서 즐겨찾기를 빠르게 연속으로 클릭하면, 클릭한 횟수만큼 즐겨찾기 POST 요청이 전송됐어요. 이로 인해 동일한 레큐 북이 여러 번 즐겨찾기에 추가되었고, 홈 페이지에서 즐겨찾기된 레큐 북을 불러오는 과정에서 에러가 발생했어요.
처음에는 이 문제를 해결하기 위해서 debounce를 도입할까 고민했지만, react-query의 isLoading을 활용해서 간단히 해결했어요.
react-query는 통신 상태를 나타내는 다양한 옵션을 제공하는데, 그중 isLoading을 활용해서 즐겨찾기 추가/ 삭제 처리 완료 여부를 확인했어요. 즐겨찾기 추가/ 삭제 처리 중이 아닐 때만 즐겨찾기 아이콘 클릭 함수가 활성화되도록 하여 중복 요청을 방지했어요.
=> [ Home/ Detail ] 레큐 북 즐겨찾기를 여러 번 눌러도 한 번만 추가되게 구현
